platform :ios, '13.0'
use_frameworks!

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCommunityHttp', :path => '../../node_modules/@capacitor-community/http'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorBackgroundRunner', :path => '../../node_modules/@capacitor/background-runner'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
  pod 'CapacitorGeolocation', :path => '../../node_modules/@capacitor/geolocation'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/@capacitor/local-notifications'
end

target 'App' do
  capacitor_pods

  # Capacitor resmi pluginler
  pod 'CapacitorApp', :path => '../../../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../../node_modules/@capacitor/browser'
  pod 'CapacitorGeolocation', :path => '../../../node_modules/@capacitor/geolocation'
  pod 'CapacitorLocalNotifications', :path => '../../../node_modules/@capacitor/local-notifications'
  pod 'CapacitorBackgroundRunner', :path => '../../../node_modules/@capacitor/background-runner'

  # Community pluginler (TEK doğru tanım)
  pod 'CapacitorCommunityHttp', :path => '../../../node_modules/@capacitor-community/http'

end
