# ios/App/Podfile - YENİ VERSİYON
platform :ios, '14.0'
use_frameworks!

# Capacitor 7 için DOĞRU YOL
pod 'Capacitor', :path => '../../../node_modules/@capacitor/core'
pod 'CapacitorCordova', :path => '../../../node_modules/@capacitor/core'
pod 'CapacitorApp', :path => '../../../node_modules/@capacitor/app'
pod 'CapacitorBrowser', :path => '../../../node_modules/@capacitor/browser'
pod 'CapacitorGeolocation', :path => '../../../node_modules/@capacitor/geolocation'
pod 'CapacitorLocalNotifications', :path => '../../../node_modules/@capacitor/local-notifications'
pod 'CapacitorCommunityHttp', :path => '../../../node_modules/@capacitor-community/http'

target 'App' do
  # Tüm pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
    end
  end
end